// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkGsxBLdPBrC92BI7vgSjg3LuCro7rM_c',
    appId: '1:513112133206:web:56c5ae23a53074aa0a35f7',
    messagingSenderId: '513112133206',
    projectId: 'gympulse-3ea43',
    authDomain: 'gympulse-3ea43.firebaseapp.com',
    storageBucket: 'gympulse-3ea43.firebasestorage.app',
    measurementId: 'G-WCHEDC76RF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZNk8rEE1EJEgXb0cunza4oJxpFVHq1QY',
    appId: '1:513112133206:android:13860ae30aecfc860a35f7',
    messagingSenderId: '513112133206',
    projectId: 'gympulse-3ea43',
    storageBucket: 'gympulse-3ea43.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDarf1DheTC7TtevDJXMko_7mwrzFScfhU',
    appId: '1:513112133206:ios:b6030130cd63ba920a35f7',
    messagingSenderId: '513112133206',
    projectId: 'gympulse-3ea43',
    storageBucket: 'gympulse-3ea43.firebasestorage.app',
    iosBundleId: 'com.example.gympulseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDarf1DheTC7TtevDJXMko_7mwrzFScfhU',
    appId: '1:513112133206:ios:b6030130cd63ba920a35f7',
    messagingSenderId: '513112133206',
    projectId: 'gympulse-3ea43',
    storageBucket: 'gympulse-3ea43.firebasestorage.app',
    iosBundleId: 'com.example.gympulseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkGsxBLdPBrC92BI7vgSjg3LuCro7rM_c',
    appId: '1:513112133206:web:2432a2a563fe55d10a35f7',
    messagingSenderId: '513112133206',
    projectId: 'gympulse-3ea43',
    authDomain: 'gympulse-3ea43.firebaseapp.com',
    storageBucket: 'gympulse-3ea43.firebasestorage.app',
    measurementId: 'G-G5HMPNHZKH',
  );
}
